
TEAM_SEASON='season'
TEAM_GAMES_PLAYED='gamesPlayed'
TEAM_GAMES_WON='gamesWon'
TEAM_IS_USER_TEAM='isUserTeam'
TEAM_PLAYERS='players'
TEAM_NAMES='names'

PLAYER_STATS='stats'
PLAYER_NAME='name'
PLAYER_ID='id'
PLAYER_HANDEDNESS='handed'
PLAYER_SEASON_BATTING='seasonBatting'
PLAYER_TEAM_BATTING='teamCareerBatting'
PLAYER_SEASON_PITCHING='seasionPitching'
PLAYER_TEAM_PITCHING='teamCareerPitching'
PLAYER_POSITION='fieldingPosition'
PLAYER_DESIGNATED_HITTER='designatedHitter'
PLAYER_PITCHING='pitching'
PLAYER_PITCHING_TYPE='pitchingType'

LEFT_HANDED=-1
RIGHT_HANDED=1

YEAR=2023
MAJOR_LEAGUE=0
LEAGUE_TYPE='l'
TEAM_ONE_ID='t0id'
TEAM_ONE_SCORE='t0score'
TEAM_TWO_ID='t1id'
TEAM_TWO_SCORE='t2score'
POST_SEASON_LEAGUES='postSeasonLeagues'
FIXTURES='fixtures'
WINNER_ID='winner'
WORLD_SERIES='final'
AL_CHAMPIONSHIP='confOneFinal'
NL_CHAMPIONSHIP='confTwoFinal'
AL_DIVISIONAL='confOneSemi{series}'
NL_DIVISONAL='confTwoSemi{series}'
AL_WILDCARD='confOneWildCard'
NL_WILDCARD='confTwoWildCard'
SERIES_LENGTH='seriesLength'
PLAYOFFS_TEAM_ONE_ID='team0id'
PLAYOFFS_TEAM_TWO_ID='team1id'


STRIKE_OUTS='strikeOuts'
AT_BATS='atBats'
SINGLES='base1'
DOUBLES='base2'
TRIPLES='base3'
HOME_RUNS='homeRuns'
CONTACT='contact'
SACRIFICE_FLYS='sacrifices'
STOLEN_BASES='stolen'
WALKS='walks'
PLATE_APPERANCES='plateApp'
NUMBER_OF_GAMES='numGames'
HITS='hits'
RBIS='runsBattedIn'
STRIKES='strikes'
BALLS='balls'
HIT_BY_PITCH='hitByPitch'
RUNS='runs'
GAMES_WON='gamesWon'
GAMES_PLAYED='gamesPlayed'

INNINGS_OUTS='inningsOuts'
PITCHES='pitches'
EARNED_RUNS='earnedRuns'

PITCHER=0
CATCHER=1
FIRST_BASE=2
SECOND_BASE=3
THIRD_BASE=4
SHORT_STOP=5
LEFT_FIELD=6
CENTER_FIELD=7
RIGHT_FIELD=8

NOT_PITCHER=-1
PITCHER_STATER=0
PTICHER_RELIEVER=1
PITCHER_CLOSER=2

PERIOD='.'
PLIST_FILE_EXT='.plist'
JSON_FILE_EXT='.json'
READ_FILE_BYTES='rb'
READ_FILE='r'
WRITE_FILE='w'
PLAIN_TXT_FILES_PATH='./app_data'

TEAM_NAMES_FILE='/UserTeamNames.json'
TEAM_FILE='/Team_{team_id}.json'
REGULAR_SEASON_DATA_FILE='/RegularSeasonData.json'
POST_SEASON_DATA_FILE='/PostSeasonData.json'

CSV_WAR='WAR'
CSV_WIN='W'
CSV_LOSS='L'
CSV_SAVES='SV'
CSV_ERA='ERA'
CSV_IP='IP'
CSV_STRIKE_OUTS='SO'