
TEAM_SEASON='season'
TEAM_GAMES_PLAYED='gamesPlayed'
TEAM_GAMES_WON='gamesWon'
TEAM_IS_USER_TEAM='isUserTeam'

PLAYER_NAME='name'
PLAYER_ID='id'
PLAYER_HANDEDNESS='handed'
PLAYER_SEASON_BATTING='seasonBatting'
PLAYER_TEAM_BATTING='teamCareerBatting'
PLAYER_SEASON_PITCHING='seasionPitching'
PLAYER_TEAM_PITCHING='teamCareerPitching'
PLAYER_POSITION='fieldingPosition'
PLAYER_DESIGNATED_HITTER='designatedHitter'

LEFT_HANDED=-1
RIGHT_HANDED=1

STRIKE_OUTS='strikeOuts'
AT_BATS='atBats'
SINGES='base1'
DOUBLES='base2'
TRIPLES='base3'
HOME_RUNS='homeRuns'
CONTACT='contact'
SACRIFICE_FLYS='sacrifices'
STOLEN_BASES='stolen'
WALKS='walks'
PLATE_APPERANCES='plateApp'
NUMBER_OF_GAMES='numGames'
HITS='hits'
RBIS='runsBattedIn'
STRIKES='strikes'
BALLS='balls'
HIT_BY_PITCH='hitByPitch'
RUNS='runs'

INNINGS_OUTS='inningsOuts'
PITCHES='pitches'
EARNED_RUNS='earnedRuns'

PITCHER=0
CATCHER=1
FIRST_BASE=2
SECOND_BASE=3
THIRD_BASE=4
SHORT_STOP=5
LEFT_FIELD=6
CENTER_FIELD=7
RIGHT_FIELD=8

NOT_PITCHER=-1
PITCHER_STATER=0
PTICHER_RELIEVER=1
PITCHER_CLOSER=2

PERIOD='.'
PLIST_FILE_EXT='.plist'
JSON_FILE_EXT='.json'
READ_FILE_BYTES='rb'
WRITE_FILE='w'
PLAIN_TXT_FILES_PATH='./app_data'